#include <MIKRODENETLEYICI_MODEL.h>
#include <stdbool.h>
#include "uygulama.h"

volatile unsigned int uygulama_kontrol;

void main(void)
{
   //....
   //....
   Uygulama_Init();
   //....
   //....
   while (1)
   {
      //....
      //....
      if (FALSE != uygulama_kontrol)
      {
         uygulama_kontrol = FALSE;
         Uygulama_Kontrol();
         //....
         //....
      }
      //....
      //....
   }
}

void Timer_ISR(void)
{
   uygulama_kontrol = TRUE;
   //....
}