/* Main.ino file generated by New Project wizard
 *
 * Created:   11 May 2019
 * Processor: ATmega328P
 * Compiler:  Arduino AVR
 */

#define BIRLER_BASAMAGI_BASLANGIC    (8)
#define ONLAR_BASAMAGI_BASLANGIC    (14)
#define YUKARI_DUGME                 (2)
#define ASAGI_DUGME                  (3)
#define LED_PIN                     (13)

static unsigned int sayac;

void setup() 
{
   unsigned int i;
   pinMode(YUKARI_DUGME, INPUT_PULLUP);
   pinMode(ASAGI_DUGME, INPUT_PULLUP);
   pinMode(LED_PIN, OUTPUT);
   sayac = 0;
   for (i = 0; i < 4; i++)
   {
      pinMode((BIRLER_BASAMAGI_BASLANGIC + i), OUTPUT);
      pinMode((ONLAR_BASAMAGI_BASLANGIC + i), OUTPUT);
   }
}

void loop() 
{
   if (LOW == digitalRead(ASAGI_DUGME))
   {
      digitalWrite(LED_PIN, HIGH);
      while (LOW == digitalRead(ASAGI_DUGME))
      {
         /* Bekle bakem*/
      }
      digitalWrite(LED_PIN, LOW);
      if (0 != sayac)
      {
         sayac--;
      }
         else
      {
         sayac = 0;      
      }
   }
   if (LOW == digitalRead(YUKARI_DUGME))
   {
      digitalWrite(LED_PIN, HIGH);
      while (LOW == digitalRead(YUKARI_DUGME))
      {
         /* Bekle bakem */
      }
      digitalWrite(LED_PIN, LOW);
      if (sayac < 99)
      {
         sayac++;
      }
      else
      {
         sayac=99;      
      }
   }
   Display(BIRLER_BASAMAGI_BASLANGIC, (sayac % 10));
   Display(ONLAR_BASAMAGI_BASLANGIC,  (sayac / 10));  
}

void Display(unsigned int ondalik,unsigned int sayi)
{
   const unsigned int b0 = (sayi & 1) ? HIGH : LOW;
   const unsigned int b1 = (sayi & 2) ? HIGH : LOW;
   const unsigned int b2 = (sayi & 4) ? HIGH : LOW;
   const unsigned int b3 = (sayi & 8) ? HIGH : LOW;

   digitalWrite(ondalik++, b0);
   digitalWrite(ondalik++, b1);
   digitalWrite(ondalik++, b2);
   digitalWrite(ondalik++, b3);
}  
  
